server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: host_api_route
          uri: http://api-interface.guershi.cn:8083 # 默认转发地址（需要实现动态路由，根据接口信息转发到对应地址）
          predicates:
            - Host=api-gateway.guershi.cn:8082
        - id: path_api_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
      default-filters: # 流量染色
        - AddResponseHeader=ershiapi, ershiapi

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: ershiapi-gateway
  protocol:
    name: dubbo
    port: -1 # 随机分配协议端口
  registry:
    address: nacos://nacos:8848

